export enum AccommodationType {
    HOTEL = "HOTEL",
    APARTMENT = "APARTMENT",
    VILLA = "VILLA",
    VACATION_HOME = "VACATION_HOME",
    GUESTHOUSE = "GUESTHOUSE",
    HOSTEL = "HOSTEL",
    BED_AND_BREAKFAST = "BED_AND_BREAKFAST",
    HOMESTAY = "HOMESTAY",
    CAMPGROUND = "CAMPGROUND",
    COUNTRY_HOUSE = "COUNTRY_HOUSE",
    BOAT = "BOAT",
    LUXURY_TENT = "LUXURY_TENT",
    CABIN = "CABIN",
    MOTEL = "MOTEL",
    RESORT = "RESORT",
    FARMSTAY = "FARMSTAY",
    CAPSULE_HOTEL = "CAPSULE_HOTEL",
    TREEHOUSE = "TREEHOUSE",
    TOWNHOUSE = "TOWNHOUSE",
    OTHER = "OTHER"
}

export enum RentalType {
    ENTIRE_PLACE = "ENTIRE_PLACE",
    PRIVATE_ROOM = "PRIVATE_ROOM",
    SHARED_ROOM = "SHARED_ROOM"
}

export enum AccommodationStatus {
    DRAFT = "DRAFT",
    PUBLISHED = "PUBLISHED",
    HIDDEN = "HIDDEN",
    BANNED = "BANNED"
}
