export enum FacilityType {
    GENERAL = "GENERAL",
    FOOD_AND_DRINK = "FOOD_AND_DRINK",
    PUBLIC_FACILITIES = "PUBLIC_FACILITIES",
    SERVICES = "SERVICES",
    SAFETY = "SAFETY",
    ACCESSIBILITY = "ACCESSIBILITY",
    ENTERTAINMENT = "ENTERTAINMENT",
    OUTDOOR = "OUTDOOR",
    TRANSPORTATION = "TRANSPORTATION",
    WELLNESS = "WELLNESS",
    SPECIAL_AMENITIES = "SPECIAL_AMENITIES",
    SUSTAINABILITY = "SUSTAINABILITY",
    OTHER = "OTHER"
}
