version: "3.9"

services:
    monolith-service:
        build:
            context: "./API/monolith-service"
            dockerfile: "Dockerfile"
        env_file:
            - ./API/monolith-service/docker.env
        ports:
            - "8080:8080"
        volumes:
            - ./API/monolith-service:/app
            - /app/node_modules
        depends_on:
            - redis
            - db
    ui:
        build:
            context: ./UI
            dockerfile: Dockerfile.dev # dev mode
        ports:
            - "5173:5173"
        volumes:
            - ./UI:/app
            - /app/node_modules
    db:
        image: mysql:8.4
        env_file:
            - ./API/common.env
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    redis:
        image: redis:8.2.1-alpine
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

volumes:
    mysql-data:
    redis-data:
