# NOTE: Run `$env:MODE="xxx";` before the docker compose ...
# with xxx in ["prod", "docker", "dev", "local"]

version: "3.9"

services:
    backend:
        build:
            context: ./API/monolith-service
            dockerfile: Dockerfile
        container_name: "backend-express"
        env_file:
            - ./API/monolith-service/.env.${MODE:-local}
        environment:
            - NODE_ENV=${MODE:-local}
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            redis:
                required: false
                condition: service_started
            db:
                required: false
                condition: service_started
    frontend:
        container_name: "frontend-react"
        build:
            context: ./UI
            dockerfile: Dockerfile.dev # dev mode
            args:
                - VITE_MODE=${MODE}
        restart: unless-stopped
        ports:
            - "3000:80"
        depends_on:
            - backend
    db:
        profiles:
            - local
        image: mysql:8.4
        container_name: mysql-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    redis:
        profiles:
            - local
        image: redis:8.2.1-alpine
        container_name: redis-cache
        restart: unless-stopped
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - redis-data:/data

volumes:
    mysql-data:
    redis-data:
