module.exports = {
	apps: [
		{
			name: "accommodation-service",
			cwd: "./API/accommodation-service",
			script: "npm",
			args: "run start",
			watch: true,
		},
		{
			name: "api-gateway",
			cwd: "./API/api-gateway",
			script: "npm",
			args: "run start",
			watch: true,
		},
		{
			name: "auth-service",
			cwd: "./API/auth-service",
			script: "npm",
			args: "run start",
			watch: true,
		},
		{
			name: "booking-service",
			cwd: "./API/booking-service",
			script: "npm",
			args: "run start",
			watch: true,
		},
		{
			name: "email-service",
			cwd: "./API/email-service",
			script: "npm",
			args: "run start",
			watch: true,
		},
		{
			name: "image-service",
			cwd: "./API/image-service",
			script: "npm",
			args: "run start",
			watch: true,
		},
		{
			name: "review-service",
			cwd: "./API/review-service",
			script: "npm",
			args: "run start",
			watch: true,
		},
		{
			name: "room-service",
			cwd: "./API/room-service",
			script: "npm",
			args: "run start",
			watch: true,
		},
		{
			name: "user-service",
			cwd: "./API/user-service",
			script: "npm",
			args: "run start",
			watch: true,
		},
	],
};
