import { EAccommodationType } from "../../../types/acommodation";
export const ACCOMMODATION_LABELS: Partial<Record<EAccommodationType, string>> = {
	[EAccommodationType.HOTEL]: "Hotel",
	[EAccommodationType.APARTMENT]: "Apartment",
	[EAccommodationType.VILLA]: "Villa",
	[EAccommodationType.VACATION_HOME]: "Vacation Home",
	[EAccommodationType.GUESTHOUSE]: "Guesthouse",
	[EAccommodationType.HOSTEL]: "Hostel",
	[EAccommodationType.BED_AND_BREAKFAST]: "Bed and Breakfast",
	[EAccommodationType.HOMESTAY]: "Homestay",
	[EAccommodationType.CAMPGROUND]: "Campground",
	[EAccommodationType.COUNTRY_HOUSE]: "Country House",
	[EAccommodationType.BOAT]: "Boat",
	[EAccommodationType.LUXURY_TENT]: "Luxury Tent",
	[EAccommodationType.CABIN]: "Cabin",
	[EAccommodationType.MOTEL]: "Motel",
	[EAccommodationType.RESORT]: "Resort",
	[EAccommodationType.FARMSTAY]: "Farmstay",
	[EAccommodationType.CAPSULE_HOTEL]: "Capsule Hotel",
	[EAccommodationType.TREEHOUSE]: "Treehouse",
	[EAccommodationType.TOWNHOUSE]: "Townhouse",
	[EAccommodationType.OTHER]: "Other ",
};

export const ACCOMMODATION_QUOTES: Partial<Record<EAccommodationType, string>> = {
	[EAccommodationType.HOTEL]: "Experience world-class service and comfort.",
	[EAccommodationType.APARTMENT]: "Enjoy the freedom of your own space with city views.",
	[EAccommodationType.VILLA]: "Indulge in luxury and privacy in your own villa paradise.",
	[EAccommodationType.VACATION_HOME]: "Create lasting memories in a cozy home away from home.",
	[EAccommodationType.GUESTHOUSE]: "Discover warm hospitality in a charming guesthouse setting.",
	[EAccommodationType.HOSTEL]: "Connect with fellow travelers in a vibrant and affordable hostel.",
	[EAccommodationType.BED_AND_BREAKFAST]: "Start your day with a delicious homemade breakfast in a welcoming B&B.",
	[EAccommodationType.HOMESTAY]: "Immerse yourself in local culture with an authentic homestay experience.",
	[EAccommodationType.CAMPGROUND]: "Reconnect with nature under the stars at a scenic campground.",
	[EAccommodationType.COUNTRY_HOUSE]: "Escape to the tranquility of a picturesque country house retreat.",
	[EAccommodationType.BOAT]: "Sail into adventure with a unique stay on a comfortable boat.",
	[EAccommodationType.LUXURY_TENT]: "Glamp in style with all the comforts in a luxurious tent.",
	[EAccommodationType.CABIN]: "Unwind in a rustic yet cozy cabin surrounded by wilderness.",
	[EAccommodationType.MOTEL]: "Convenient and comfortable roadside stays for the weary traveler.",
	[EAccommodationType.RESORT]: "Pamper yourself with endless amenities at a premier resort.",
	[EAccommodationType.FARMSTAY]: "Experience rural life and fresh air on a charming farmstay.",
	[EAccommodationType.CAPSULE_HOTEL]: "Efficient and modern sleeping pods for the urban explorer.",
	[EAccommodationType.TREEHOUSE]: "Elevate your stay with a magical treehouse adventure.",
	[EAccommodationType.TOWNHOUSE]: "Live like a local in a stylish and spacious townhouse.",
	[EAccommodationType.OTHER]: "Explore unique accommodations tailored to your adventure.",
};

export const ACCOMMODATION_HERO_IMAGES: Partial<Record<EAccommodationType, string>> = {
	[EAccommodationType.HOTEL]: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.APARTMENT]: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.VILLA]: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.VACATION_HOME]: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.GUESTHOUSE]: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.HOSTEL]: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.BED_AND_BREAKFAST]:
		"https://media.gettyimages.com/id/148764549/photo/teapot-shaped-sign-outside-bed-and-breakfast.jpg?s=2048x2048&w=gi&k=20&c=OXn8vcuko8yULVVepR5Tbli_uCoareL-_92OcPS5JJg=",
	[EAccommodationType.HOMESTAY]: "https://plus.unsplash.com/premium_photo-1676321046262-4978a752fb15?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.CAMPGROUND]: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.COUNTRY_HOUSE]: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.BOAT]: "https://plus.unsplash.com/premium_photo-1680831748248-47616728ee9f?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.LUXURY_TENT]: "https://images.unsplash.com/photo-1714326029322-fcc1464df757?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.CABIN]: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.MOTEL]: "https://images.unsplash.com/photo-1600375235940-76fb0f15b010?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.RESORT]: "https://plus.unsplash.com/premium_photo-1675039871139-06cc792da9a7?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.FARMSTAY]: "https://plus.unsplash.com/premium_photo-1667566903049-c48abf0a2414?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.CAPSULE_HOTEL]: "https://images.unsplash.com/photo-1661683508913-b6bb64235147?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.TREEHOUSE]: "https://images.unsplash.com/photo-1759106219589-ba827d49f1a4?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.TOWNHOUSE]: "https://plus.unsplash.com/premium_photo-1725408025985-4e2a24c03133?w=1600&auto=format&fit=crop&q=80",
	[EAccommodationType.OTHER]: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1600&auto=format&fit=crop&q=80",
};

// Keep basic cities structure but they can be enhanced dynamically in App.tsx
export const CITY_NAMES = ["Da Nang", "Ho Chi Minh City", "Hanoi", "Hoi An", "Phu Quoc", "Nha Trang", "Da Lat", "Sapa"];
