export enum AmenityType {
    COMFORT = "COMFORT",
    ENTERTAINMENT = "ENTERTAINMENT",
    BATHROOM = "BATHROOM",
    KITCHEN = "KITCHEN",
    SAFETY = "SAFETY",
    ACCESSIBILITY = "ACCESSIBILITY",
    WORKSPACE = "WORKSPACE",
    OUTDOOR = "OUTDOOR",
    OTHER = "OTHER"
}
