syntax = "proto3";

package image;

import "google/protobuf/empty.proto";

service ImageService {
    rpc GetHealth(google.protobuf.Empty) returns (HealthResponse);
    rpc UploadImages(UploadRequest) returns (UploadResponse);
    rpc GetImages(GetImageRequest) returns (GetImageResponse);
}

message HealthResponse {
    string service = 1;
    bool success = 2;
}

message UploadRequest{
    string entityId = 1;
    EEntityType entityType = 2;
    repeated FileData files = 3;
}

message UploadResponse{
    bool success = 1;
    repeated UploadedImage images = 2;
}

message UploadedImage {
    string id = 1;
    string s3Key = 2;
    string variant = 3; // THUMBNAIL, WEBP, OPTIMIZED
}

message FileData {
    string filename = 1;
    string mimeType = 2;
    bytes data = 3;
}

enum EEntityType{
    USER_PROFILE = 0;
    ACCOMMODATION = 1;
    ROOM = 2;
    REVIEW = 3;
}

message GetImageRequest{
    EEntityType entityType = 1;
    string id = 2;
}

message GetImageResponse {
    repeated ResponseImage images = 1;
}

message ResponseImage {
    string id = 1;
    string url = 2;
    EVariantType variant = 3;
    string imageId = 4;
}

enum EVariantType {
    ORIGINAL = 0;
    THUMBNAIL = 1;
    WEBP = 2;
    OPTIMIZED = 3; 
}