export enum PaymentTransferStatus {
	PENDING = "PENDING",
	DISMISSED = "DISMISSED",
	FAILED = "FAILED",
	COMPLETED = "COMPLETED",
	PARTIALLY_HALFED = "PARTIALLY_HALFED",
	PARTIALLY_THIRDED = "PARTIALLY_THIRDED",
	PARTIALLY_QUARTERED = "PARTIALLY_QUARTERED",
}
